//Main App page actions.
export const TOOGLE_HAMBURGER_MENU = 'TOOGLE_HAMBURGER_MENU';
export const CLOSE_HAMBURGER_MENU = 'CLOSE_HAMBURGER_MENU';
export const HANDLE_STATE_CHANGE_HAMBURGER_BURGER = 'HANGLE_STATE_CHANGE_HAMBURGER_BURGER';


//modal actions
export const LOGOUT_MODAL = 'LOGOUT_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

//Asset Actions
export const CREATE_ASSET_SUCCESS="CREATE_ASSET_SUCCESS";


//diagram actions
export const GET_DIAGRAM_DATA_SUCCESS= 'GET_DIAGRAM_DATA_SUCCESS';
